name: Tag

on:
  workflow_dispatch:

jobs:
  build_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.HHFRANCOIS }}
      - uses: actions/setup-node@v1.4.3
      - run: git config --global user.name '$GITHUB_ACTOR'
      - run: git config --global user.email '$GITHUB_ACTOR@users.noreply.github.com'
      - run: npm version patch -m "release from $GITHUB_RUN_NUMBER"
      - run: git push --follow-tags
